### ISSUE TITLE
GamerOS doesn't boot.

### ISSUE THREAD

**Issue by dubigrasu** [alkazar/gamer-os#1] opened 2019-03-26 01:58 UTC
Following our conversation on reddit, after a third attempt the system is again successfully installed but fails to boot.
 
At boot time the message:
"Reboot and select the proper boot device, or insert Boot media in selected boot device and press enter"
is displayed.

I attach here the terminal output including all my executed commands during the installation, and the install.sh's output.
The terminal output is more complete (there's also a "lspci" in there) and includes specific error messages about the grub-install sequence. (from line 593)
[script_output.log](https://github.com/alkazar/gamer-os/files/3006157/script_output.log)
[terminal_output.log](https://github.com/alkazar/gamer-os/files/3006159/terminal_output.log)
Sorry about the weird characters, is still readable though.

**Comment by alkazar** [comment] 2019-03-26 03:47
From the grub error, it looks like the problem is that we are installing in legacy mode, but the partition table is type GPT instead of MBR. I have pushed a fix to the master branch, can you try again?

I must have happened to test with disks that were already MBR or that had no partition table. I had mistakenly thought `sfdisk` was taking care of setting up the correct partition table, but it seems that `sfdisk` won't touch the partition table if it already exists, which makes sense.

**Comment by dubigrasu** [comment] 2019-03-26 05:17
Yes, success, this time it boots properly.
The log says:
installing grub...                                                                                                                            
Generate your bootloader configuration with:
  grub-mkconfig -o /boot/grub/grub.cfg
Optional dependencies for grub
    freetype2: For grub-mkfont usage
    fuse2: For grub-mount usage
    dosfstools: For grub-mkrescue FAT FS and EFI support
    efibootmgr: For grub-install EFI support
    libisoburn: Provides xorriso for generating grub rescue iso using grub-mkrescue
    os-prober: To detect other OSes when generating grub.cfg in BIOS systems
    mtools: For grub-mkrescue FAT FS support
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the info directory file...
Installing for i386-pc platform.
Installation finished. No error reported.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
done

**Comment by alkazar** [comment] 2019-03-26 11:36
Awesome, thanks for your help!

**Closed by alkazar** 2019-03-26 11:36 UTC
